### PR TITLE
Resolving some issues from the tracker and some updates

### PR DESCRIPTION
**Pull request by Davidy22**
Fixes for #24, #26 and #28, start of pre-commit hooks for cleanliness with a passthrough of black, dep version bump and associated fixes. The addition of pre-commit hooks and the associated auto-formatting are in commit bc42b1b2f52580ba2ff440aa92a1a6d6a8bb6cc1

### CODE REVIEW

**Comment by Naramsim** [comment]
Hmm, why Travis hasn't run? Can you please configure your fork to run Travis @Davidy22?

**Comment by Naramsim** [comment]
Mmm, it seems that Travis has switched from `.org` to `.com` and I cannot link anymore this project...

Maybe a good time to switch to GH Actions?

**Comment by Davidy22** [comment]
Enabled travis on the repo and made a cursory commit, green check and all. May add an action some time to run pre commit on github side too

**Review by GregHilmes — APPROVED** [review]
It all looks good. Thanks for contributing!

**Pull request merged**
