### PR TITLE
Add unit tests on GH Actions

### PR DESCRIPTION
**Pull request by Naramsim**
Travis-ci has switched from `.org` to `.com` so I thought we could get rid of it and start using Actions.

So this PR tests Pokebase on Python 3.6 and 3.7 on Actions.

### CODE REVIEW

**Review by GregHilmes — APPROVED** [review]

**Comment by Davidy22** [comment]
I enabled 3.8 and 3.9 on my branch that has a bunch of dependency version bumps and the check passed. My pull request that contains version bumps have been merged, so this probably works if you pull from main and try 3.8 again.

**Review by Kronopt — APPROVED** [review]
Looks good to me!

**Comment by Naramsim** [comment]
I've added a job for checking the syntax with `flake8`

**Comment by aditya-yadav-27** [comment]
hey can anybody help me with how can i print the stats of a given pokemon? (sorry for dumb question)

**Comment by Naramsim** [comment]
@aditya-yadav-27 

```py
import pokebase as pb

for stat in pb.pokemon('charmander').stats:
  print('{}: {}'.format(stat.stat.name, stat.base_stat))
```

https://replit.com/@AlessandroPezze/OpulentUtilizedAudit#main.py

**Comment by aditya-yadav-27** [comment]
> @aditya-yadav-27
> 
> ```python
> import pokebase as pb
> 
> for stat in pb.pokemon('charmander').stats:
>   print('{}: {}'.format(stat.stat.name, stat.base_stat))
> ```
> 
> https://replit.com/@AlessandroPezze/OpulentUtilizedAudit#main.py

if i want to store all the stats values separately so how can i do that?

**Comment by aditya-yadav-27** [comment]
does searching pokemon from its id is not working?

**Comment by Davidy22** [comment]
For one, you probably want to open an issue for this instead of post in a closed pull request. Also, can you provide the code that doesn't work for you so we can see what's happening?

**Comment by aditya-yadav-27** [comment]
k sorry for that btw I can't understand how to print the evolution line of a pokemon can anyone help me with this?

**Pull request merged**
